# Secret key used to secure sessions
play.http.secret.key="SecretKeyCortexProjectSOCMiniCodespace123"

# Elasticsearch configuration
search {
  index = cortex
  uri = "http://elasticsearch:9200"
}

# Analyzers configuration
analyzer {
  urls = [
    "https://download.thehive-project.org/analyzers.json"
  ]
}

# Responders configuration
responder {
  urls = [
    "https://download.thehive-project.org/responders.json"
  ]
}
